name: Build, Test, and Push

on: [push]

env:
  IMAGE_NAME: student_service
  REPO_NAME: souitch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Run docker-compose services
      run: |
        docker-compose up -d --build

    - name: Check running services
      run: docker-compose ps

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag and Push image to Docker Hub Container Registry
      run: | 
        docker tag $REPO_NAME/$IMAGE_NAME $REPO_NAME/$IMAGE_NAME:latest
        docker push $REPO_NAME/$IMAGE_NAME:latest

    - name: Cleanup
      run: docker-compose down
